apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 0%
  template:
    metadata:
      labels:
        app: web
    spec: 
      containers:
        - name: web
          image: raian13/otus-kuber-202103:hw1
          volumeMounts:
            - mountPath: /app
              name: app
            - mountPath: /test1
              name: test1
          livenessProbe:
            tcpSocket: { port: 8000 }
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8000
      initContainers:
        - name: init-web
          image: busybox:1.31.0
          command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
          volumeMounts:
            - mountPath: /app
              name: app
      volumes:
          - name: app
            emptyDir: {}
          - name: test1
            emptyDir: {}
