apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx-custom
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
  - protocol: TCP
    port: 9113
    targetPort: 9113
    name: metrics
