apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-custom
  labels:
    team: frontend
    monitoring: enabled
spec:
  selector:
    matchLabels:
      app: nginx-custom
  endpoints:
  - port: metrics