apiVersion: v1
kind: Pod
metadata:
  name: tmpapp
  labels:
    app: tmpapp
spec:
  serviceAccountName: vault-auth
  containers:
    - name: tmpapp
      image: burtlo/devwebapp-ruby:k8s
      env:
        - name: VAULT_ADDR
          value: "http://vault:8200"
        - name: VAULT_TOKEN
          value: root
