apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 3
  template: 
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: server
          image: raian13/hipster-frontend:1.1
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-readiness-probe"
          env:
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "product-catalog-service:3550"
          - name: CURRENCY_SERVICE_ADDR
            value: "currency-service:7000"
          - name: CART_SERVICE_ADDR
            value: "cart-service:7070"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "recommendation-service:8080"
          - name: CHECKOUT_SERVICE_ADDR
            value: "checkout-service:5050"
          - name: SHIPPING_SERVICE_ADDR
            value: "shipping-service:50051"
          - name: AD_SERVICE_ADDR
            value: "ad-service:9555"