apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  replicas: 3
  template: 
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: server
          image: raian13/hipster-paymentservice:1.1
