apiVersion: v1
kind: Pod
metadata:
  name: test-minio
  labels:
    app: test-minio
spec:
  containers:
  - name: mc
    image: minio/mc
    command: ["/bin/bash"]
    args: ["-c", "while true; do sleep 10; done"]
